on: [push]

jobs:
  test:
    runs-on: codeberg-tiny
    strategy:
      matrix:
        ruby-version: ['3.3', '4.0']
    container:
      image: ruby:${{ matrix.ruby-version }}
    steps:
      - run: git clone --depth 1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} .

      - run: curl -fsSL https://bun.sh/install | bash
      - run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bundle install
          rake test
